spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
    show-sql: true
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true

server:
  port: 3000
logging:
  level:
    org:
      elasticsearch: trace
